<!-- laser -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!--1.constants-->
    <xacro:property name="lidar_radius" value="0.06" />
    <xacro:property name="lidar_height" value="0.05" />

    <xacro:property name="lidar_joint_x" value="0.08" />
    <xacro:property name="lidar_joint_y" value="0.0" />
    <xacro:property name="lidar_joint_z" value="${car_height/2 + lidar_height/2}" />
    <!--2.link and joints-->
    <link name="virtual_car1_laser">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
            </geometry>
            <material name="pink_blue">
                <color rgba="0.4 0.78 1.0 0.8"/>
            </material>

        </visual>
    </link>

    <joint name="lidar2base_link" type="fixed">
        <parent link="virtual_car1_base_link"/>
        <child link="virtual_car1_laser"/>
        <origin xyz="${lidar_joint_x} ${lidar_joint_y} ${lidar_joint_z}"/>
    </joint>
</robot>